version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - petclinic-net

  petclinic-app:
    build: .
    container_name: petclinic-app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/petclinic?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - petclinic-net

  jenkins:
    build: ./jenkins
    container_name: jenkins
    privileged: true
    user: root
    environment:
      - NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL}
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    networks:
      - petclinic-net
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - petclinic-net

volumes:
  mysql-data:
  jenkins-home:

networks:
  petclinic-net:
    driver: bridge
