version: '3.8'

services:
  # CONTAINER 1: O Banco de Dados MySQL
  mysql-db:
    image: mysql:8.0
    container_name: petclinic-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # CONTAINER 2: A sua aplicação Spring PetClinic
  petclinic-app:
    image: henryblh/petclinic:v1 # Puxando a imagem que você subiu pro Docker Hub
    container_name: petclinic-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://petclinic-mysql:3306/petclinic
    depends_on:
      - mysql-db

    restart:
      on-failure

# Requisito do projeto: Uso correto de volumes para persistência de dados
volumes:
  mysql_data:
