version: '3.8'

services:

  # CONTAINER 1: Banco de Dados MySQL
  mysql-db:
    image: mysql:8.0
    container_name: petclinic-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - petclinic-net

  # CONTAINER 2: Aplicação Spring PetClinic
  petclinic-app:
    image: henryblh/petclinic:v1
    container_name: petclinic-app
    restart: on-failure

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/petclinic

    depends_on:
      - mysql-db

    networks:
      - petclinic-net

  # CONTAINER 3: Jenkins
  jenkins:
    build: ./jenkins
    container_name: jenkins
    privileged: true
    user: root

    environment:
      NOTIFICATION_EMAIL: ${NOTIFICATION_EMAIL}

    ports:
      - "8081:8080"
      - "50000:50000"

    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace

    depends_on:
      - mailhog

    networks:
      - petclinic-net

  # CONTAINER 4: MailHog
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog

    ports:
      - "1025:1025"
      - "8025:8025"

    networks:
      - petclinic-net

volumes:
  mysql_data:
  jenkins-home:

networks:
  petclinic-net:
    driver: bridge
